### ISSUE TITLE
How to use jquery-filter-json-plugin with multiple property and multiple values in large json

### ISSUE THREAD

**Issue by touch2hussain** [kapilkashyap/jquery-filter-json-plugin#4]
[
    {
        "machineId": "1A",
        "serialNo": "123",
        "city": "",
        "Mode": "ON"
    },
    {
        "machineId": "2B",
        "serialNo": "123",
        "city": "",
        "Mode": "OFF"
    },
    {
        "machineId": "3A",
        "serialNo": "123",
        "city": "NewCity",
        "Mode": "OFF"
    },
    {
        "machineId": "1A",
        "serialNo": "123",
        "city": "",
        "Mode": "OFF"
    },
      {
        "machineId": "1A",
        "serialNo": "123",
        "city": "",
        "Mode": "Default"
    }
]

in above json, lets say i want to filter, machineId  having value "IA", and Mode having values "ON and OFF"

I tried something like 

 property: ["machineId", "Mode"],
  value: ["1A,ON,OFF"],

it did not work, Please suggest how to use the plugin in this case

**Comment by kapilkashyap** [comment]
Try passing the values as an array of strings like so -

value: ["1A","ON","OFF"]

**Comment by johibkhan** [comment]
@touch2hussain Did the issue get resolved?

**Comment by kapilkashyap** [comment]
@touch2hussain Did the issue get resolved?

**Comment by kapilkashyap** [comment]
Closing this issue.
