### ISSUE TITLE
Is there a way to use "value" of nested object as  "property" 

### ISSUE THREAD

**Issue by prashantsani** [kapilkashyap/jquery-filter-json-plugin#5]
Hello!

Lets consider following JSON format.

```
var dummyJSON = [
    {
        "id":"",
        "additionalProp":{
            "filterName":"name",
            "filterValue":"XYZ" 

        }
    }
]
```

What if I want to filter based on additionalProp['filterName']==="name" ??

Following code fils to work

```
filter = $.fn.filterJSON(dummyJSON, {
      property: [additionalProp['filterName']==="name" ], 
      wrapper: true,
      value: ["XYZ"],
      checkContains: false,
      startsWith: true,
      matchCase: false,
      avoidDuplicates: true,
      sort: false
});
```

Thanks.

**Comment by kapilkashyap** [comment]
Hey Prashant,

We iterate through each property at a time. We would not know the child
properties until next iteration. So this would not work.

But yeah, noting it down as an enhancement :)

Thanks & Regards,
Kapil Kashyap

**Comment by kapilkashyap** [comment]
Closing this issue.
