### ISSUE TITLE
Retrieve The main Object Instead of child

### ISSUE THREAD

**Issue by prashantsani** [kapilkashyap/jquery-filter-json-plugin#6]
Consider following Array

```
var dummyJSON = [
    {
        "id":"123",
        "additionalProp":{
            "name":"XYZ",
            "designation":"Manager",
            "hobbies":"Football"
        }
    },
    {
        "id":"345",
        "additionalProp":{
            "name":"ABC",
            "designation":"XYZ",
            "hobbies":"Cricket"
        }
    }
]
```

Now, if I type following,

```
var x = $.fn.filterJSON(dummyJSON, {
      property: ["name"],     
      value: ["XYZ"],
      wrapper: true,
      checkContains: false,
      startsWith: true,
      matchCase: false,
      avoidDuplicates: true,
      sort: false
});
```

I get _additionalProp_ of 1st object, not the whole object.

value of x 

```
            {
            "name":"XYZ",
            "designation":"Manager",
            "hobbies":"Football"
            }
```

expected value of x

```
    {
        "id":"123",
        "additionalProp":{
            "name":"XYZ",
            "designation":"Manager",
            "hobbies":"Football"
        }
    }

```

**Comment by kapilkashyap** [comment]
Hey Prashant,

You can either get the value of the property itself (if wrapper is set to
false) or the parent of the property (if wrapper is set to true).

To get the desired result, you could instead search for id property (which
would be a better approach) with wrapper set to true. The config would be:

var x = $.fn.filterJSON(dummyJSON, {
    property: ["id"],
    value: ["123"],
    wrapper: true,
    checkContains: false,
    startsWith: true,
    matchCase: false,
    avoidDuplicates: true,
    sort: false
});

Hope this helps.

I am responding using a mobile so the formatting might be a mess. Sorry!

Regards,
Kapil Kashyap

**Comment by kapilkashyap** [comment]
Closing this issue!
